=== Branimir123/FMI-XML/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="leagues">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="league">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="id" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="clubs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="club">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
					<xs:element name="year_established">
					  <xs:simpleType>
						<xs:restriction base="xs:integer">
						  <xs:minInclusive value="1800"/>
						  <xs:maxInclusive value="2018"/>
						</xs:restriction>
					  </xs:simpleType>
					</xs:element>                    
					<xs:element name="league">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="league_id" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:byte" name="league_thophys"/>
                    <xs:element type="xs:string" name="owner"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="player_id" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="player">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:byte" name="number"/>
              <xs:element name="club">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="club_id" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="age">
				  <xs:simpleType>
					<xs:restriction base="xs:integer">
					  <xs:minInclusive value="0"/>
					  <xs:maxInclusive value="120"/>
					</xs:restriction>
				  </xs:simpleType>
			  </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Branimir123/FMI-XML/footballCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
	<?xml-stylesheet type="text/xsl" href="xsl.xsl"?>
	<catalog xsi:schemaLocation="schema.xsd">
	  <leagues>
		<league id="l1">Premier League</league>
		<league id="l2">Primera División (La Liga)</league>
		<league id="l3">First Professional Football League</league>
	  </leagues>

	  <clubs>
		<club id="c1" player_id="ch1 ch2 ch3 ch4 ch5">
		  <name>Chelsea</name>
		  <year_established>1905</year_established>
		  <league league_id="l1">Premier League</league>
		  <league_thophys>6</league_thophys>
		  <owner>Roman Abramovich</owner>
		</club>
		<club id="c2" player_id="m1 m2 m3 m4 m5">
		  <name>Manchester United</name>
		  <year_established>1878</year_established>
		  <league league_id="l1">Premier League</league>
		  <league_thophys>20</league_thophys>
		  <owner>Manchester United plc</owner>
		</club>
		<club id="c3" player_id="a1 a2 a3 a4 a5">
		  <name>Arsenal</name>
		  <year_established>1886</year_established>
		  <league league_id="l1">Premier League</league>
		  <league_thophys>13</league_thophys>
		  <owner>Arsenal Holding plc</owner>
		</club>
		<club id="c4" player_id="mc1 mc2 mc3 mc4 mc5">
		  <name>Manchester City</name>
		  <year_established>1880</year_established>
		  <league league_id="l1">Premier League</league>
		  <league_thophys>2</league_thophys>
		  <owner>Owner	City Football Group</owner>
		</club>

		<club id="c5" player_id="b1 b2 b3 b4 b5">
		  <name>Barcelona</name>
		  <year_established>1899</year_established>
		  <league league_id="l2">La Liga</league>
		  <league_thophys>24</league_thophys>
		  <owner>Registered association</owner>
		</club>
		<club id="c6" player_id="r1 r2 r3 r4 r5">
		  <name>Real Madrid</name>
		  <year_established>1902</year_established>
		  <league league_id="l2">La Liga</league>
		  <league_thophys>33</league_thophys>
		  <owner>Registered association</owner>
		</club>

		<club id="c7" player_id="cs1 cs2 cs3">
		  <name>CSKA</name>
		  <year_established>1948</year_established>
		  <league league_id="l3">First Professional Football League</league>
		  <league_thophys>31</league_thophys>
		  <owner>Grisha Ganchev</owner>
		</club>
			<club id="c8" player_id="l1 l2 l3">
		  <name>Levski</name>
		  <year_established>1914</year_established>
		  <league league_id="l3">First Professional Football League</league>
		  <league_thophys>26</league_thophys>
		  <owner>Spas Rusev</owner>
		</club>
	  </clubs>
	
			<!-- Chelsea players-->
			<player id="ch1">
			  <name>David Luiz</name>
			  <number>30</number>
			  <club club_id="c1"></club>
			  <age>30</age>
			</player>
			<player id="ch2">
			  <name>Álvaro Morata</name>
			  <number>9</number>
			  <club club_id="c1"></club>
			  <age>25</age>
			</player>
			<player id="ch3">
			  <name>Eden Hazard</name>
			  <number>10</number>
			  <club club_id="c1"></club>
			  <age>27</age>
			</player>
			<player id="ch4">
			  <name>Thibaut Courtois</name>
			  <number>13</number>
			  <club club_id="c1"></club>
			  <age>30</age>
			</player>
				<player id="ch5">
			  <name>Pedro</name>
			  <number>11</number>
			  <club club_id="c1"></club>
			  <age>30</age>
			</player>

			<!-- Man United players-->
				<player id="m1">
			  <name>David de Gea</name>
			  <number>1</number>
			  <club club_id="c2"></club>
			  <age>30</age>
			</player>
			<player id="m2">
			  <name>Paul Pogba</name>
			  <number>6</number>
			  <club club_id="c2"></club>
			  <age>23</age>
			</player>
			<player id="m3">
			  <name>Juan Mata</name>
			  <number>8</number>
			  <club club_id="c2"></club>
			  <age>29</age>
			</player>
			<player id="m4">
			  <name>Zlatan Ibrahimović</name>
			  <number>10</number>
			  <club club_id="c2"></club>
			  <age>36</age>
			</player>
				<player id="m5">
			  <name>Anthony Martial</name>
			  <number>11</number>
			  <club club_id="c2"></club>
			  <age>22</age>
			</player>

			<!-- Arsenal players-->
			<player id="a1">
			  <name>Alexis Sánchez</name>
			  <number>7</number>
			  <club club_id="c3"></club>
			  <age>29</age>
			</player>
			<player id="a2">
			  <name>Aaron Ramsey</name>
			  <number>8</number>
			  <club club_id="c3"></club>
			  <age>27</age>
			</player>
			<player id="a3">
			  <name>Mesut Özil</name>
			  <number>11</number>
			  <club club_id="c3"></club>
			  <age>29</age>
			</player>
			<player id="a4">
			  <name>Theo Walcott</name>
			  <number>14</number>
			  <club club_id="c3"></club>
			  <age>28</age>
			</player>
				<player id="a5">
			  <name>Héctor Bellerín</name>
			  <number>24</number>
			  <club club_id="c3"></club>
			  <age>22</age>
			</player>

			<!-- Manchester City players-->
			<player id="mc1">
			  <name>Claudio Bravo</name>
			  <number>1</number>
			  <club club_id="c4"></club>
			  <age>34</age>
			</player>
			<player id="mc2">
			  <name>Raheem Sterling</name>
			  <number>7</number>
			  <club club_id="c4"></club>
			  <age>23</age>
			</player>
			<player id="mc3">
			  <name>Sergio Agüero</name>
			  <number>10</number>
			  <club club_id="c4"></club>
			  <age>29</age>
			</player>
			<player id="mc4">
			  <name>Kevin De Bruyne</name>
			  <number>17</number>
			  <club club_id="c4"></club>
			  <age>26</age>
			</player>
				<player id="mc5">
			  <name>David Silva</name>
			  <number>21</number>
			  <club club_id="c4"></club>
			  <age>32</age>
			</player>

			<!-- Barcelona players-->
			<player id="b1">
			  <name>Lionel Messi</name>
			  <number>10</number>
			  <club club_id="c5"></club>
			  <age>30</age>
			</player>
			<player id="b2">
			  <name>Andrés Iniesta</name>
			  <number>8</number>
			  <club club_id="c5"></club>
			  <age>33</age>
			</player>
			<player id="b3">
			  <name>Luis Suárez</name>
			  <number>9</number>
			  <club club_id="c5"></club>
			  <age>30</age>
			</player>
			<player id="b4">
			  <name>Gerard Piqu</name>
			  <number>3</number>
			  <club club_id="c5"></club>
			  <age>30</age>
			</player>
				<player id="b5">
			  <name>Sergio Busquets</name>
			  <number>5</number>
			  <club club_id="c5"></club>
			  <age>29</age>
			</player>

			<!-- Real Madrid players-->
			<player id="r1">
			  <name>Cristiano Ronaldo </name>
			  <number>7</number>
			  <club club_id="c6"></club>
			  <age>32</age>
			</player>
			<player id="r2">
			  <name>Karim Benzema</name>
			  <number>9</number>
			  <club club_id="c6"></club>
			  <age>30</age>
			</player>
			<player id="r3">
			  <name>Luka Modrić</name>
			  <number>10</number>
			  <club club_id="c6"></club>
			  <age>32</age>
			</player>
			<player id="r4">
			  <name>Marcelo</name>
			  <number>12</number>
			  <club club_id="c6"></club>
			  <age>29</age>
			</player>
				<player id="r5">
			  <name>Casemiro</name>
			  <number>14</number>
			  <club club_id="c6"></club>
			  <age>25</age>
			</player>

			<!-- CSKA players-->
			<player id="cs1">
			  <name>Fernando Karanga</name>
			  <number>9</number>
			  <club club_id="c7"></club>
			  <age>26</age>
			</player>
			<player id="cs2">
			  <name>Nikolay Bodurov</name>
			  <number>5</number>
			  <club club_id="c7"></club>
			  <age>31</age>
			</player>
			<player id="cs3">
			  <name>Kiril Despodov</name>
			  <number>19</number>
			  <club club_id="c7"></club>
			  <age>21</age>
			</player>

			<!-- Levski players-->
			<player id="l1">
			  <name>Junior Mapuku</name>
			  <number>10</number>
			  <club club_id="c7"></club>
			  <age>28</age>
			</player>
			<player id="l2">
			  <name>Jordi Gómez</name>
			  <number>13</number>
			  <club club_id="c7"></club>
			  <age>32</age>
			</player>
			<player id="l3">
			  <name>David Jablonský</name>
			  <number>28</number>
			  <club club_id="c7"></club>
			  <age>26</age>
			</player>

	</catalog>
